import { createClient } from '@supabase/supabase-js';
// Database types will be generated by Supabase CLI in a real project

// To avoid TS errors before 'types/supabase' exists, we'll cast.
// Realistically, the user needs to generate types using `supabase gen types typescript`.
// For now, we will use a generic client.

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
    console.warn('Missing Supabase Environment Variables');
}

export const supabase = createClient(
    supabaseUrl || '',
    supabaseAnonKey || ''
);
